[package]
name = "lampo"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
actix = "0.13"
actix-web = "4"
actix-web-actors = "4"
actix-rt = "2"
actix-files = "0.6.0"
tokio = { version = "1", features = ["full"] }